name: Web App CI

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:6.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongosh --eval 'db.runCommand({ ping: 1 })'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Load environment variables
        run: |
          pip install python-dotenv
          python -c 'from dotenv import load_dotenv; load_dotenv()'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Lint with pylint
        run: |
          pylint backend/app/run.py

      - name: Format check with black
        run: |
          black --check backend/app

      - name: Run tests and check coverage
        working-directory: backend
        run: |
          pytest --cov=app ./app/tests/

      - name: Docker Compose up
        run: docker-compose up --build

